#pragma once

// 蓝牙LED配置
#ifndef CONFIG_BLUETOOTH_LED_BLINK_INTERVAL
#define CONFIG_BLUETOOTH_LED_BLINK_INTERVAL 1000
#endif

// 状态协调器配置
#ifndef CONFIG_CHARGING_HAS_PRIORITY
#define CONFIG_CHARGING_HAS_PRIORITY 1
#endif

// LED控制器配置
#ifndef CONFIG_LED_CONTROLLER_STACK_SIZE
#define CONFIG_LED_CONTROLLER_STACK_SIZE 1024
#endif

// 充电监控器配置
#ifndef CONFIG_CHARGING_GPIO_PIN
#define CONFIG_CHARGING_GPIO_PIN 9
#endif

#ifndef CONFIG_CHARGING_POLL_INTERVAL_CHARGING_MS
#define CONFIG_CHARGING_POLL_INTERVAL_CHARGING_MS 2000
#endif

#ifndef CONFIG_CHARGING_POLL_INTERVAL_FULL_MS
#define CONFIG_CHARGING_POLL_INTERVAL_FULL_MS 10000
#endif

// 功能启用宏
#ifdef CONFIG_CUSTOM_BLUETOOTH_LED
#define ENABLE_BLUETOOTH_LED 1
#else
#define ENABLE_BLUETOOTH_LED 0
#endif

#ifdef CONFIG_CUSTOM_STATE_COORDINATOR
#define ENABLE_STATE_COORDINATOR 1
#else
#define ENABLE_STATE_COORDINATOR 0
#endif

#ifdef CONFIG_CUSTOM_LED_CONTROLLER
#define ENABLE_LED_CONTROLLER 1
#else
#define ENABLE_LED_CONTROLLER 0
#endif

#ifdef CONFIG_CUSTOM_CHARGING_MONITOR
#define ENABLE_CHARGING_MONITOR 1
#else
#define ENABLE_CHARGING_MONITOR 0
#endif